/*
 * Copyright © 2017 Ericsson India Global Services Pvt Ltd. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package org.opendaylight.netvirt.bgpmanager.api;

@SuppressWarnings("checkstyle:TypeName")
public enum af_afi implements org.apache.thrift.TEnum {
    AFI_IP(1),
    AFI_IPV6(2),
    AFI_L2VPN(3);

    private final int value;

    af_afi(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    public static af_afi findByValue(int value) {
        switch (value) {
            case 1:
                return AFI_IP;
            case 2:
                return AFI_IPV6;
            case 3:
                return AFI_L2VPN;
            default:
                return null;
        }
    }
}

